# Generated by Django 3.0.7 on 2020-06-27 04:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200627_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
