# Generated by Django 3.0.7 on 2020-06-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'pizzas'), ('S', 'sides'), ('D', 'drinks')], default='P', max_length=2),
        ),
    ]
