# Generated by Django 3.0.7 on 2020-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200625_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('P', 'pizza'), ('S', 'side'), ('D', 'drink')], default='P', max_length=2),
        ),
    ]
